module.exports = {
    BASEROUTEMSG : "Server has been started successfully",
    EMAILEXISTS : "User with this email already exists.",
    EMAILNOTEXISTS: "User with entered email address is not registered.",
    INVALIDPASSWORD: "Invalid Password",
    INVALIDJWTTOKEN : "Invalid Token",
    LOGINFAILED: "Login Failed",
    REGISTRATIONFAILED : "Registration Failed",
    STATUSNOTFOUND : 400,
    STATUSNOTAUTHORIZED : 401,
    INTERNALERRORSTATUS : 500,
    STATUSOK: 200,
    STATUSCREATED : 201,
    HASHALGO: "sha256",
    HASHENCODING: "hex",
    CRYPTOBYES : 20,
    MINUTES: 20,
    SECONDS: 60,
    MILLISECONDS: 1000,
    EMAILSUBJECT: "Flexi-Gym Portal Password reset token",
    EMAILBODY : "Please click on the below link to proceed with completing your password reset process for Flexi-Gym Portal. \n\n ",
    RESETEMAILSENT : "Password reset link sent successfully on your email address.",
    RESETEMAILERROR: "Error occurred while sending password reset email.",
};